server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /blog
spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n.blog
  datasource:
    username: root
    password: 1230
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&charactorEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    #开启驼峰命名映射
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: 配置XML文件位置

    #建表语句
#    initialization-mode: always
#    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
#    schema:
#      - classpath:sql/blog.sql
#      - classpath:sql/topic.sql

blog.root.username: root
blog.root.password: 12345